### ISSUE TITLE
Creating a package/library

### ISSUE THREAD

**Issue by thanabgithub** [keosariel/Programming-language-in-python-using-llvmlite#2]
Hi, 
My name is Thana. I'm a naive Python user. Sorry if my question sounds silly. 
Is it possible to create a package or something that I can import to use in Python?

The use case is that I can do for loop in via a package created from your language instead of doing for loop via  NumPy in order to speed up my calculation.

I'm really interested in this language because the syntax is simple and it looks easy to use.

**Comment by keosariel** [comment]
Hello Thana,

Unfortunately, the language is just a basic proof of concept and not really production-ready. However, it can be done since the language is compiled to LLVM and the LLVMLITE lib allows you to import LLVM based functions.

Though there has been a request to build a fully functional language and I think I'd take it into consideration. SInce I have seen a few people interested.

**Comment by keosariel** [comment]
Hello Thana,

Firstly, sorry for the late reply! And however what you asked can be done,
since the language compiles to llvm and you can make use of llvm functions
in the python using the llvmlite lib.

If I didn’t answer your question properly, just contact me again. Your
questions are still welcome!

**Comment by thanabgithub** [comment]
Hi Kaosariel,
Thank you for your reply. I will play with it and share the result with you about my use case.
